Add bookings
CyberCoHuK/java-shareit pull request #2
Opened 2023-07-13 16:14 UTC by CyberCoHuK

2023-07-14 05:09 UTC, Frilock requested changes
Андрей, в целом довольно хорошая работа. Пара небольших комментариев и можно принимать

2023-07-14 05:09 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDtoShort.java
> +    @PositiveOrZero(message = "itemID не может быть меньше ноля")
itemId

2023-07-14 05:09 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    private final Sort sort = Sort.by("start").descending();
Типы сортировок предложил бы тоже вынести в енам

2023-07-14 05:09 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            case "ALL":
Используйте вместо литералов енам

2023-07-14 05:09 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (text.isBlank()) {
Лучше через StringUtils проверять

2023-07-14 05:09 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        Collection<BookingDtoItem> bookings = bookingRepository.findAllByItem(item, sort)
streamApi конструкции пишут обычно так
stream()
.filter
.collect

2023-07-14 05:09 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    private final UserServiceImpl userService;
Зачем инжектите реализацию? Было правильно, через интерфейс

2023-07-14 05:09 UTC, Frilock commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users
Честно говоря не очень нравиться форматирование скриптов (лучше бы выравнивание добавить), но не критично
Кроме того, смотрите вы для полей задаете максимальный размер и дополнительные флаги типо Not null. Вообще эти ограничения принято указывать также в аннотации Column в вашем классе модели. Чтобы заранее понимать какие ограничения у поля и не лезть в скрипт лишний раз

2023-07-14 08:38 UTC, CyberCoHuK commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    private final UserServiceImpl userService;
В начале чет не собирался проект и эксперементировал, потом забыл убрать

2023-07-15 08:35 UTC, Frilock approved these changes
Доброе утро, пара небольших комментариев, но в целом принимаю, поправьте потом

2023-07-15 08:35 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @Column(name = "status", nullable = false)
Еще размерность принято указывать - lenght

2023-07-15 08:35 UTC, Frilock commented on src/main/java/ru/practicum/shareit/enums/Sorts.java
> +    START(Sort.by("start").descending());
Вообще не очень решение, я предлагал просто значение сортировки в енам вынести
START("start")

2023-07-15 08:35 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                .stream()
stream можно на той же строке оставлять

2023-07-20 15:17 UTC, merged