First Iteration
CyberCoHuK/java-shareit pull request #4
Opened 2023-08-03 16:33 UTC by CyberCoHuK

2023-08-03 19:41 UTC, Frilock requested changes
Андрей, крутая работа, по ревью комментариев в целом и нет почти, все очень здорово. Пара мелких моментов и принимаем

2023-08-03 19:41 UTC, Frilock commented on gateway/src/main/java/ru/practicum/shareit/BaseClient.java
> +            if (parameters != null) {
Можно заменить на тернарное выражение, будет компактнее

2023-08-03 19:41 UTC, Frilock commented on gateway/src/main/java/ru/practicum/shareit/exceptions/ExceptionsHandler.java
> +@Slf4j
Лишняя аннотация

2023-08-03 19:41 UTC, Frilock commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private static final String USER_ID_HEADER = "X-Sharer-User-Id";
static final поля располагают выше final полей

2023-08-04 08:31 UTC, CyberCoHuK commented on gateway/src/main/java/ru/practicum/shareit/BaseClient.java
> +            if (parameters != null) {
Попробую, правда это класс от практикума, главное ничего в нем не сломать :D

2023-08-04 14:29 UTC, Frilock approved these changes
Андрей, здорово.

2023-08-06 08:03 UTC, merged